name: ebrary
services:
  ebrarydb:
    image: 'mysql:8.0.33'
    container_name: 'ebrarydb'
    env_file: '.env.development'
    ports:
      - '3307:3306'
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - type: volume
        source: ebrarydb
        target: /var/lib/mysql
volumes:
  ebrarydb:
