export type BookThemeType =
  | 'LOVE_AND_PASSION'
  | 'FRIENDSHIP_AND_HUMAN_RELATION'
  | 'QUEST_FOR_IDENTITY'
  | 'GOOD_AND_EVIL'
  | 'LIBERTY_AND_OPPRESSION'
  | 'TRAVEL_EXPLORATION'
  | 'WAR_CONSEQUENCES'
  | 'JUSTICE_INJUSTICE'
  | 'FANTASY_AND_SUPERNATURAL'
  | 'SCIENCE_PROGRESS_AND_EXCESSES'
  | 'DREAM_IMAGINARY'
  | 'TIME_MEMORY'
  | 'LONELINESS_ISOLATION'
  | 'FAMILLY_HERITAGE'
  | 'DESTINY_FREEWILL'
  | 'OTHER';

export const BookThemeValues: BookThemeType[] = [
  'LOVE_AND_PASSION',
  'FRIENDSHIP_AND_HUMAN_RELATION',
  'QUEST_FOR_IDENTITY',
  'GOOD_AND_EVIL',
  'LIBERTY_AND_OPPRESSION',
  'TRAVEL_EXPLORATION',
  'WAR_CONSEQUENCES',
  'JUSTICE_INJUSTICE',
  'FANTASY_AND_SUPERNATURAL',
  'SCIENCE_PROGRESS_AND_EXCESSES',
  'DREAM_IMAGINARY',
  'TIME_MEMORY',
  'LONELINESS_ISOLATION',
  'FAMILLY_HERITAGE',
  'DESTINY_FREEWILL',
  'OTHER',
];
