export type TargetAudienceType =
  | 'ACADEMIC'
  | 'ENTERTAINMENT'
  | 'PERSONAL_DEVELOPMENT'
  | 'COMMITTED_AND_SOCIAL'
  | 'FOREIGN_CULTURE'
  | 'VISUALLY_IMPAIRED'
  | 'PEOPLE_WITH_READING_DIFFICULTIES'
  | 'OTHER';

export const TargetAudienceValues: TargetAudienceType[] = [
  'ACADEMIC',
  'ENTERTAINMENT',
  'PERSONAL_DEVELOPMENT',
  'COMMITTED_AND_SOCIAL',
  'FOREIGN_CULTURE',
  'VISUALLY_IMPAIRED',
  'PEOPLE_WITH_READING_DIFFICULTIES',
  'OTHER',
];
